var child = [
  { 'dupe': true, 'type': 16, 'name': 'confirm_transfer.php', 'dir': 'c0', 'linked': 2, 'url': 'http://localhost/create_transfer.php/confirm_transfer.php', 'fetched': true, 'code': 200, 'len': 100, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xce62b6d7 },
  { 'dupe': true, 'type': 16, 'name': 'Glowna.sfish', 'dir': 'c1', 'linked': 2, 'url': 'http://localhost/create_transfer.php/Glowna.sfish', 'fetched': true, 'code': 200, 'len': 100, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xce62b6d7 },
  { 'dupe': true, 'type': 16, 'name': 'Konta', 'dir': 'c2', 'linked': 2, 'url': 'http://localhost/create_transfer.php/Konta', 'fetched': true, 'code': 200, 'len': 100, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xce62b6d7 },
  { 'dupe': true, 'type': 16, 'name': 'Kwota', 'dir': 'c4', 'linked': 2, 'url': 'http://localhost/create_transfer.php/Kwota', 'fetched': true, 'code': 200, 'len': 100, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xce62b6d7 },
  { 'dupe': true, 'type': 16, 'name': 'logout.php', 'dir': 'c6', 'linked': 2, 'url': 'http://localhost/create_transfer.php/logout.php', 'fetched': true, 'code': 200, 'len': 100, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xce62b6d7 },
  { 'dupe': true, 'type': 16, 'name': 'Nr.sfish', 'dir': 'c7', 'linked': 2, 'url': 'http://localhost/create_transfer.php/Nr.sfish', 'fetched': true, 'code': 200, 'len': 100, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xce62b6d7 },
  { 'dupe': true, 'type': 16, 'name': 'pr', 'dir': 'c8', 'linked': 2, 'url': 'http://localhost/create_transfer.php/pr', 'fetched': true, 'code': 200, 'len': 100, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xce62b6d7 },
  { 'dupe': true, 'type': 16, 'name': 'to.sfish', 'dir': 'c10', 'linked': 2, 'url': 'http://localhost/create_transfer.php/to.sfish', 'fetched': true, 'code': 200, 'len': 100, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xce62b6d7 },
  { 'dupe': true, 'type': 16, 'name': 'Tytul.sfish', 'dir': 'c11', 'linked': 2, 'url': 'http://localhost/create_transfer.php/Tytul.sfish', 'fetched': true, 'code': 200, 'len': 100, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xce62b6d7 }
];
