var child = [
  { 'dupe': false, 'type': 4, 'name': 'create_transfer.php', 'dir': 'c0', 'linked': 5, 'url': 'http://localhost/create_transfer.php/', 'fetched': true, 'code': 200, 'len': 742, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'UTF-8', 'missing': false, 'csens': true, 'child_cnt': 7, 'issue_cnt': [ 9, 5, 1, 0, 2 ], 'sig': 0xe310c694 },
  { 'dupe': false, 'type': 8, 'name': 'welcome.php', 'dir': 'c1', 'linked': 5, 'url': 'http://localhost/welcome.php', 'fetched': true, 'code': 200, 'len': 101, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 5, 'issue_cnt': [ 7, 1, 0, 0, 3 ], 'sig': 0x289a25dc },
  { 'dupe': false, 'type': 16, 'name': 'confirm_transfer.php', 'dir': 'c2', 'linked': 0, 'url': 'http://localhost/confirm_transfer.php', 'fetched': true, 'code': 200, 'len': 100, 'decl_mime': 'text/html', 'sniff_mime': 'application/binary', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xce62b6d7 },
  { 'dupe': false, 'type': 16, 'name': 'create_transfer.php', 'dir': 'c3', 'linked': 2, 'url': 'http://localhost/create_transfer.php', 'fetched': true, 'code': 200, 'len': 100, 'decl_mime': 'text/html', 'sniff_mime': 'application/binary', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x5878cd80 },
  { 'dupe': false, 'type': 16, 'name': 'index.php', 'dir': 'c6', 'linked': 2, 'url': 'http://localhost/index.php', 'fetched': true, 'code': 200, 'len': 99, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': false, 'type': 16, 'name': 'login.php', 'dir': 'c7', 'linked': 2, 'url': 'http://localhost/login.php', 'fetched': true, 'code': 200, 'len': 419, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x4200ad0b },
  { 'dupe': false, 'type': 16, 'name': 'logout.php', 'dir': 'c8', 'linked': 2, 'url': 'http://localhost/logout.php', 'fetched': true, 'code': 200, 'len': 63, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': false, 'type': 16, 'name': 'registration.php', 'dir': 'c9', 'linked': 5, 'url': 'http://localhost/registration.php', 'fetched': true, 'code': 200, 'len': 633, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 4, 'issue_cnt': [ 8, 0, 0, 0, 0 ], 'sig': 0x41f3e13f },
  { 'dupe': false, 'type': 16, 'name': 'transfer_history.php', 'dir': 'c10', 'linked': 2, 'url': 'http://localhost/transfer_history.php', 'fetched': true, 'code': 200, 'len': 148, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xce62b6d7 },
  { 'dupe': true, 'type': 16, 'name': 'welcome.php', 'dir': 'c11', 'linked': 2, 'url': 'http://localhost/welcome.php', 'fetched': true, 'code': 200, 'len': 101, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xce62b6d7 },
  { 'dupe': false, 'type': 16, 'name': 'welcome.php', 'dir': 'c13', 'linked': 2, 'url': 'http://localhost/welcome.php', 'fetched': true, 'code': 200, 'len': 101, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 1 ], 'sig': 0x306174ce }
];
