var child = [
  { 'dupe': false, 'type': 4, 'name': 'Konta', 'dir': 'c0', 'linked': 0, 'url': 'http://localhost/create_transfer.php/Konta/', 'fetched': true, 'code': 200, 'len': 742, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 1, 0, 0, 0 ], 'sig': 0x9ce12342 },
  { 'dupe': true, 'type': 4, 'name': 'Kwota', 'dir': 'c1', 'linked': 0, 'url': 'http://localhost/create_transfer.php/Kwota/', 'fetched': true, 'code': 200, 'len': 742, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x9ce12342 },
  { 'dupe': true, 'type': 4, 'name': 'pr', 'dir': 'c2', 'linked': 0, 'url': 'http://localhost/create_transfer.php/pr/', 'fetched': true, 'code': 200, 'len': 742, 'decl_mime': 'text/html', 'sniff_mime': 'text/html', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x9ce12342 },
  { 'dupe': false, 'type': 8, 'name': 'confirm_transfer.php', 'dir': 'c3', 'linked': 5, 'url': 'http://localhost/create_transfer.php/confirm_transfer.php', 'fetched': true, 'code': 200, 'len': 742, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 4, 1, 0, 0, 2 ], 'sig': 0xf1b07434 },
  { 'dupe': false, 'type': 8, 'name': 'Glowna.sfish', 'dir': 'c4', 'linked': 0, 'url': 'http://localhost/create_transfer.php/Glowna.sfish', 'fetched': true, 'code': 200, 'len': 742, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 1, 0, 0, 0 ], 'sig': 0x9ced2342 },
  { 'dupe': true, 'type': 8, 'name': 'Konta.sfish', 'dir': 'c5', 'linked': 0, 'url': 'http://localhost/create_transfer.php/Konta.sfish', 'fetched': true, 'code': 200, 'len': 742, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x9ced2342 },
  { 'dupe': true, 'type': 8, 'name': 'Kwota.sfish', 'dir': 'c6', 'linked': 0, 'url': 'http://localhost/create_transfer.php/Kwota.sfish', 'fetched': true, 'code': 200, 'len': 742, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x9ced2342 },
  { 'dupe': false, 'type': 8, 'name': 'logout.php', 'dir': 'c7', 'linked': 2, 'url': 'http://localhost/create_transfer.php/logout.php', 'fetched': true, 'code': 200, 'len': 742, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xce7ab6d7 },
  { 'dupe': true, 'type': 8, 'name': 'Nr.sfish', 'dir': 'c8', 'linked': 0, 'url': 'http://localhost/create_transfer.php/Nr.sfish', 'fetched': true, 'code': 200, 'len': 742, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x9ced2342 },
  { 'dupe': true, 'type': 8, 'name': 'pr.sfish', 'dir': 'c9', 'linked': 0, 'url': 'http://localhost/create_transfer.php/pr.sfish', 'fetched': true, 'code': 200, 'len': 742, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x9ced2342 },
  { 'dupe': true, 'type': 8, 'name': 'to.sfish', 'dir': 'c10', 'linked': 0, 'url': 'http://localhost/create_transfer.php/to.sfish', 'fetched': true, 'code': 200, 'len': 742, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x9ced2342 },
  { 'dupe': true, 'type': 8, 'name': 'Tytul.sfish', 'dir': 'c11', 'linked': 0, 'url': 'http://localhost/create_transfer.php/Tytul.sfish', 'fetched': true, 'code': 200, 'len': 742, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x9ced2342 },
  { 'dupe': true, 'type': 8, 'name': 'welcome.php', 'dir': 'c12', 'linked': 2, 'url': 'http://localhost/create_transfer.php/welcome.php', 'fetched': true, 'code': 200, 'len': 742, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xce7ab6d7 }
];
